language: python
env:
  global:
  - secure: m4hKzjkR7MlEEZVLRISMQWGFlHs37vDVuQ4M32YkOXP1JsG2yPeQzE53YvRtbhciCJ1pWqMAtj50g2MF25YhrvijsjoqLptq3JhhOEpBBmUtH03w892kd8Tlj/0QtRUV1ldWo0TlU5LbJ8+TUDrXE5i3Ni0WeITFxoxG8f1+KW0sh7OLJUbrkG4ObZm4cxE3mZcvzfyOlzaXj2wt3SELwVD6XVqBimz8rG9wOn+p0NEsfVlj2hbnXIBDJFwLt2fE/xxEYRb1z6o392TGm7M2N0wTgU90RRw6CYAzmG8fk1UeIs77tKkF9gLsXtQEKSNmkjSk3jqED7zPy1SwwVvxvVbtC7Xn9qOmbq6ftho4lu8huVXr8aFQH4nCwVzjsMoHbvZEbvMh8B9OeMzUJ9e7xodv3AWymAZXSg7AAt4JQVSOwG8/Dw0OGkK9WU2RXY46nMYLTtygW7bwh9XnMPLp1CVo6piftPUbmlz70TZm0lYQ/umvBaRxq2wQeA/G9qpZ29aUJCjWz/LA3SZiHSXqxU4nXhX1uPaRCy6XkMWCn0m6HhK3P0BESOZJpwoOUXL81tm98crw21704IGy/FzZHf11r8Xqb2hj9bqxrjb+wL/tuBYMA0G/QB2I/u8PfPlwwnEmoAh/6woA32WWLRjwrnsK9gz+Uj6a0wqST4A9Lw0=
  - secure: TugalJ/JeQOxxBqzavO38C0sG8v1QG0dKAwvfs2ib9x4LFnKuUqx4KcMy3Od2yn7ISpqKmKs9tWIH6WVdusEwFbdQz8jO2aIU3OgE9AJ1K9D5DpkyEPN84G1b/acKHkCVUsnAICalm8W/4K6N8nP65FObxhCCJTTV1mFL92jPOSeJLAgB5om8u84JWgJi/p0FtWrJJkwWTM9n4a9uIaFyF9p6OX5PmJ9gmneoFCuHIUHqFnLc1xuB2H97dnhduq8TbbcYGTFlx+4i2lAjqN/YjJ5QteUVdUdlyEoR3KNE/FoG84nWEYH7z4MKWT4cIkySmwC6Fi9SHdO0tiMWGN24AKIfjduzeHeSBLLNpJoKynfbd1H8h2gtCfrbonmQi+pJnkHQczMc6WE6PF9KvelkgKEnYVquM7/MkdqJjB2LBXXoymKFRrYt174RTjNQ55ld63qt/HYfGERPJh3n9U0F1GPQSNX25Gbw7PAzIGR/UcKsbgnTKcH0xlqdcLZJjXUvQ8P5nhtWtax5aFTV/PBuFE8PIpmO4UMfCz91bYhYG+iaUJ2PwRSRvSjPfBTeoWXpi063HDc5DX3mVYKj3XOl9gUMtNaN9u5ekvXJ8wF+eXo7iS6kdNm2OIfDrc2WXGwy7s+BJXnjNaC7eGkYcXNh6E/fMOVFSsYf6qnHCm+KXw=
  - AWS_REGION=us-west-2
  - secure: JJLsDc8wy6ByQcno+ZrdUcbwCe4cY9v8Kk0kVFvEV5qdDB+1Ua1WHXosBgBHqF7TgSAoS/Ep9fxyuCtLNnvs2T27AM9igKAW07tv9kCLQltrZJwmK72gNQCIGSBfbc5YN7QWomXorOamo+CnVVkwXrJAevec8gkzBR6cgpxXL7tsMxrYVHEmzYU2fzUsWcmT55hXYgTiMxZaYSLxC2Ki9CEZ9QXJHQf7kt37UUXIgN5MJRgLZGPeB7iSS6D+k8E895QS9VJqqWMzQ/V+g0JEm7Jsr7WzYTSLXoTXtIUTaEkM71frktQpoG04DuAJhzKslwIF58HHtZPtrfbYVszcP3ZkRPYleN0lNFbEjFfosgM/aZP99s/FwFoWidskJrhN5lfFZxEw2yVGPDRGHQSiyKWGdJoGmEQKT6B7QeYBTOQhQF+gnb3xvlkT5zkpgXAMgjdPrTktM36Eyj9QTgHxOa5yKN/fCJYC65S9AY1HcWeqaFPQwAEjTnxjKNSE1ovF6qz8rAPttsVxZQ79RVRRFq+hWsVQysf57iMBQh51PgOrBFVQeaUv8QIo8sbrCS3xTmwntd73EKVo6+vyFI2fHUCPVRbq3/i33hr14M+BDUJmNjo79su7DSi27HqvQcaL2hsyt735Byl25TV4ebm8QrXFHrnkhx3b3+BmCS+Ap3U=
  - secure: YVblcovM6MSZcmDiOkhSD8lYnZs6AlPtFQKkg0HcJpN/sc7K8C2s9WXLPy7JSWxKU4mZCdnk30ixxGp9K42GjX5aR9MSoBhOkLGtrbBW+mqWXUdKuoQZYc6ef/HnZIuth5Nij39Ox7pg/Amf5ZSHpCnP9yyBVaS/oIAlhytltAUCdxtj52JJHKRRQoGsmoW3+QXj2flncG29JdVhL2gYVwRZaAIcYR5+lUjU8sBOSe9cRq/iUqXaNqIefbRZnJoiQx2fwnj0Ctib8yniieTPXWrFfyyvPJyjRSi9vSSvS+MgC87sKciA3TIW/YVosVC7aYzEZV96/JB9yxZSqA0Jp1OHpZHSzC4Qx10gNKs85JWtL2y67hpYLt/4+v4O7jvtZZCXwqBrd54hmDHTqn38N57hHw1d8o59yljotixnOb1vJp8gPGy25rpHt7XVJuy7CQ3qfiAiNy3y7FfAZ+/h2CY3RI7/kd5PbCxgCnxTj+aAHH0N6DJ5x06wZV2bZZUrvjpGN+nrJrNvU1eqbfmCgMFFa/srNMwjs7+ifGQqSjkIZiz+UsPsXmg8aaLHyeAqhS56LMAikN5U4ffSJyVk2S/v6G71Oxsk+IFfdH0unBLpoQmfXOcDgh+3ZrdM8z2XUlMsEAuoIvw9MacPvv3uFUgGEbLqwmiy/aZB+j4K6iQ=
  - secure: iOHFTbk3Gv3Du4U1ewZL8H41+WCxTM6Y38GJ5lwwPclE1v0x0zng+4niNBMhxuvksn+W1Xhr1555uNVjPJHaZIl0YWNALHWOJe8uxOifGa/eioQYoGIi/PqRLKrT6sTYrvQZyZTWkgzHMguWMXwRS5bSplNYIZPPLvnrO36CBZ/hqCKvnJghW7x6JeEVgvn0Y0ZK7xeJ+gL3lG5IT1x9vpI8m0uEGQ2T+aYgbDF92sogQpfo7x3QnQr20W6ahrV+lLk+6NpskTNmj5clcM7RbmUL7+/bDPYk89Qy8Ke2FkH56qhF1DigcyW74AQqTiqnaZy5ufumMrqYRU+b6CK3KNSIL80iwVtce2ZQaV8oLgtui7JHe7Fnx86sYWnA75hlPcS67qy7vs/Gy3DIUyA27E3xAjjyAHtdMfaycXFOdG8EcutiZBaIdxMZ8wOz3zk45xChwM4oV1WIo5/PfqOaOECgJBM0tbVq8OuL7cj+hMTKdjJUNIxpSO5aVr4Hj6qP/12UBnxTxuSdczJ0liEC8N2JaMVP07LyTRD+eem+WDr+iZInK9m0zajK4sJzSjOpIwFCsewWyUHokHalL4pEeugPeo2SYjfKzLKDomLENIecIV88YQEMcC+7InxTUTu6+/JVPS3udqIjmpPLiHFONNlHn1ek4Cjx7EDfxW4+yCE=
  - secure: BGlRC9SGLTLuFip3mDaUxTc0GFkgYriyFW/2VRYboM7OxD+lGK3enpVsbRSvRxkxLJYIXhNJOiS6yztVB6v3GwESxGtX4o/30PcgARvljAx+n36Y3Wg9HcJCLI3Q9slGpPCEQiOmDcxyJm/IIE8KOjCq040AhgsfL7OWnv73uJrOerc3nKyUXoDr70z60VGtk76DxB0jkBDA/HQHuaLLUYLWiKCRgMLKY0tRKUl3Ns2SzT6BDD7ilcI5KaReo9b0qEf2W/0kMVrSt1tSkFtFZLBeZlaVUsLjbkhSkPJlvNEjM0fQcHQEmKCYVZn1dN32lUBr1tGxcWqSfd+RqfpcHKHb6eS241szxpagqvtgUqzCe5XAodXf7OAYOYSHE8NsyP7xBedYMtAXp7JC4V2JTs16C6S4idrQLl0jd56hA/1xR8KjN1iSH+YEBj6mgbHTqvaA30M4xtNNwdzyNq5tLtD5XoiwQol7ltalaOg1dRQDZobNvcS09csbgtoOdMEXe2AM1rleFsvPuvbhhOW/+t5H9+Z6iktJ5PDxphTH7fxOBUQq6D34oTQ7SxWYsFLlo6q3NafEHTMC3f9RRsScdCOYn0ypHxH7/a27foj5VGbgdK5f2olWFHfUboNsP2gpLyHLbiIByc1FUsCpzJkWfCgFTSqk+mR08Wl6T3G4gow=
python:
- 3.6
install:
- echo Install
script:
- echo Ok
before_deploy:
- cd src
- zip -r -D ../deploy.zip .
- cd ..
deploy:
- provider: lambda
  access_key_id: "$PROD_AWS_ACCESS_KEY_ID"
  secret_access_key: "$PROD_AWS_SECRET_ACCESS_KEY"
  function_name: kinesis-data-preprocessor
  region: "$AWS_REGION"
  handler_name: lambda_function.lambda_handler
  runtime: python2.7
  publish: true
  zip: deploy.zip
  role: arn:aws:iam::$PROD_AWS_ACCOUNT_ID:role/lambda-data-preprocessor
  timeout: 60
  on:
    branch: master
- provider: lambda
  access_key_id: "$DEV_AWS_ACCESS_KEY_ID"
  secret_access_key: "$DEV_AWS_SECRET_ACCESS_KEY"
  function_name: kinesis-data-preprocessor
  region: "$AWS_REGION"
  handler_name: lambda_function.lambda_handler
  runtime: python2.7
  publish: true
  zip: deploy.zip
  role: arn:aws:iam::$DEV_AWS_ACCOUNT_ID:role/lambda-data-preprocessor
  timeout: 60
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
notifications:
  slack:
    secure: L8uTA3R8LoPdcI+Wxi2asy9Kq6Ge6Wx/fkZKzp3TBL9lUH2khPWnfL2a663pKwaMPNntJcj2aKggBU6xl3eKSweS+r6DdFxb1Jl7KGjatWcGmpFuysh8tKd5ICKSLdc2a1sempFDNNwT0SzS0K/T9lXhEbxs0AaWcfkuG0x2ZjBhO22RPUe4JiF5guQO8cR8Zmpf1qbOWl12N1wgcRJKknL226EyNa1ypP59a8JZZtODx5emXWZjo3XnonpfVBejAqq4YEV9wKoymMWHhMJAi+GYrg5KU1Neq9ejHT9xCpWsTlA5IvO/HAfmz7RsceCuQ8UTimmOErv62hotlgO3LP2GDyf9b5nJOCQgGAyOfn9iPnk+nZig+qww7b+C+/yvgrdBQzpS5sC8hikYr5dwAomhIhzg9xKxUAqKMI59wCwiG1118svHhN8HOHj0lYFEcwrMkXF7OOPBgUL4tgpgqKrjc6kZeZgPvKC9M3wWFBxsNq6n4rXfT0OsUq9fcxYSYw3gVwvgju8vXm7jqV02GP9rOFI1X+ju+IzLkSCHCH8oEUBQiFrWj4XKkwXYLdRYRxbLJSv+DamJwU4pW5JpfBrDbEwxxXAoIqcMXeZB/bqMcdw6Z4Y5tUup3XcZUT/blaV3+2zs0vfEArdh6pvTaMxUQw/qbxvmem0b4M8fEhI=
