language: python

python:
  - 3.6

install:
  - echo Install

script:
  - echo Ok

before_deploy:
  - zip -r deploy.zip .

deploy:
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    function_name: kinesis-data-preprocessor
    region: us-west-2
    handler_name: lambda_function.lambda_handler
    runtime: python3.6
    publish: true
    zip: deploy.zip
    role: $ROLE
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    function_name: kinesis-data-preprocessor
    region: us-west-2
    handler_name: lambda_function.lambda_handler
    runtime: python3.6
    publish: true
    zip: deploy.zip
    role: $ROLE
    on:
      branch: master
