AWSTemplateFormatVersion: 2010-09-09

Resources:

  KinesisDataProcessorRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'lambda-data-preprocessor'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'AWS::AccountId'

  KinesisDataProcessorPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'lambda-data-preprocessor-policy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogGroup'
            -  'logs:CreateLogStream'
            -  'logs:PutLogEvents'
            Resource:
            - 'arn:aws:logs:*:*:*'
      Roles:
        - !Ref KinesisDataProcessorRole